Repository gdsc-ssu/cs-study, pull requests merged in 2022-12, with the labels that each got.

#21 add: study about Heap structure
  자료구조/Heap.md
Labels: data-structure

#19 add: study about http message
  네트워크/HTTP message.md
Labels: network

#28 add : study about greedy
  알고리즘/greedy.md
Labels: algorithm

#18 add : study about sql-basic-syntax
  데이터베이스/SQL 기본 문법.md
Labels: database

#27 add: study about Lock in OS
  운영체제/Lock.md
Labels: os

#35 add: study about balanced binary search tree
  자료구조/Balanced Binary Search Tree.md
Labels: data-structure

#31 add : study about transaction
  데이터베이스/Transaction.md
Labels: database

#34 add : study about File System
  운영체제/FileSystem.md
Labels: os

#29 add : study about Dijkstra
  알고리즘/Dijkstra.md
Labels: algorithm

#40 add: study about Kruskal
  알고리즘/Kruskal.md
Labels: algorithm

#39 add : study about socket programming
  소켓 프로그래밍.md
Labels: network

#30 add : study about network core
  네트워크 코어.md
Labels: network

#38 add : study about normalization
  데이터베이스/정규화.md
Labels: database

#33 add : study about IPC
  운영체제/IPC.md
Labels: os
