Repository gdsc-ssu/cs-study, pull requests merged in 2022-11, with the labels that each got.

#1 add: study about osi-7-layer
  네트워크/OSI 7계층.md
Labels: network

#2 add : study about http&https
  네트워크/HTTP & HTTPS.md
Labels: network

#5 add: study about sort, dfs/bfs
  알고리즘/DFS,BFS.md
  알고리즘/정렬.md
Labels: algorithm

#9 add: study about cpu-scheduling
  운영체제/CPU scheduling.md
Labels: os

#3 add : study about linked-list
  자료구조/Linked List.md
Labels: data-structure

#10 add : study about database-concept-summary
  데이터베이스/DB 개념 정리.md
Labels: database

#6 add: study about dynamic-programming
  알고리즘/다이나믹 프로그래밍(DP).md
Labels: algorithm

#12 add : study about process&thread
  운영체제/프로세스와 스레드.md
Labels: os

#8 add : study about BST
  자료구조/BinarySearchTree.md
Labels: data-structure

#11 add: study about HTTP-method
  네트워크/HTTP method.md
Labels: network

#14 add: study about floyd warshall
  알고리즘/floyd-warshall.md
Labels: algorithm

#13 add : study about Cache memory
  네트워크/cache.md
Labels: os

#24 add : study about paging&segmentation
  운영체제/paging&segmentation.md
Labels: os

#32 add : study about Cache memory
  운영체제/Cache.md
Labels: os

#26 add : study about sync-async
  운영체제/sync & async.md
Labels: os

#25 add : study about Interrupt
  운영체제/Interrupt.md
Labels: os
