Repository gdsc-ssu/cs-study, pull requests merged in 2023-03, with the labels that each got.

#23 add : study about edge network
  네트워크/edge network .md
Labels: network

#72 add: study about lis
  알고리즘/LIS.md
Labels: algorithm

#74 add: study about MVC pattern
  디자인패턴/MVC-pattern.md
Labels: design-pattern

#73 add : study about ci/cd
  소프트웨어공학/CI-CD.md
Labels: software-engineering

#69 add : study about Agile,Waterfall
  소프트웨어공학/애자일과 워터풀.md
Labels: software-engineering

#60 add : study about Monotone Stack
  알고리즘/Monotone Stack.md
Labels: algorithm

#75 add : study about SQL & NoSQL
  데이터베이스/SQL&NoSQL.md
Labels: database

#66 add : study about Adapter
  디자인패턴/Adapter.md
Labels: design-pattern

#42 add : study about LoadBalancing
  네트워크/Load Balancing.md
Labels: network
